version: '3'
services:
  web:
    build: './r'
    ports:
      - "8787:8787"
      - "3838:3838"
    volumes:
    # Path on the host, relative to the Compose file
      - ./R:/srv/shiny-server
    networks:
        my_app_network:
            ipv4_address: 172.28.1.2
networks:
    my_app_network:
        ipam:
            driver: default
            config:
                - subnet: 172.28.0.0/16